import { MemoryTypedDraftStore, MemoryTypedSessionBackend, TypedOneTapSessionCoordinator, captureF3FixtureHtml, createTypedInspectionBatch, MemoryF3RetentionStore, expiryAfterSevenDays, discardF3Capture } from '../../src/prototype/phase11-typed-one-tap-api.mjs';
import { fullFixture, partialFixture, unusableFixture } from './fixtures.mjs';

const root=document.querySelector('#screen');
const draftStore=new MemoryTypedDraftStore(), backend=new MemoryTypedSessionBackend();
const session=new TypedOneTapSessionCoordinator({draftStore,backend}); const retention=new MemoryF3RetentionStore();
const writerId=`f3-fixture:${crypto.randomUUID()}`; let chosen=null, busy=false, activeCapture=null;
function render(title,text,actions=[],note='') { root.replaceChildren(); const h=document.createElement('h2'),p=document.createElement('p');h.textContent=title;p.textContent=text;root.append(h,p);if(note){const n=document.createElement('p');n.className='small';n.textContent=note;root.append(n);} for(const action of actions){const b=document.createElement('button');b.textContent=action.label;b.disabled=busy;b.addEventListener('click',action.click);root.append(b);} }
function stopped(error){render('このstageでは安全に保存できません',error?.message??String(error),[], '保存済みの結果は変更していません。');}
async function select(fixture,label){ if(busy)return;busy=true;chosen={fixture,label};render('準備中','自作fixtureの計画を作成しています。');try{await session.start({eventId:fixture.expectedEventId,eventName:label,writerId,plan:[{id:`stage:${fixture.expectedStageId}`,kind:'stage-page',stageId:fixture.expectedStageId,url:fixture.url,label}]});busy=false;render('対象fixture page','まだcapture・scan・保存は実行していません。',[{label:'このstageを確認',click:capture}],'ownerの明示tap後だけ、固定済みHTML snapshotを1回取得します。');}catch(error){busy=false;stopped(error);}}
async function capture(){if(busy)return;busy=true;render('確認中','immutable snapshotをcaptureし、分類・保存・read-back照合しています。');try{const ticket=await session.beginCapture({writerId,currentUrl:chosen.fixture.url});const captureId=`f1-f3-${chosen.fixture.expectedStageId}-${crypto.randomUUID()}`;const result=await captureF3FixtureHtml({session,ticket,eventHtml:chosen.fixture.eventHtml,expectedEventId:chosen.fixture.expectedEventId,expectedStageId:chosen.fixture.expectedStageId,captureInput:{readUrl:()=>chosen.fixture.url,readOuterHTML:()=>chosen.fixture.stageHtml,captureId,now:()=>new Date().toISOString()}});activeCapture=result.scan.capture;await retention.save({captureId,createdAt:activeCapture.observedAt,expiresAt:expiryAfterSevenDays(activeCapture.observedAt),refs:{sessionId:(await session.load()).sessionId,classification:result.classification}});busy=false;const reviewAction={label:'取得結果を確認',click:openReview},discardAction={label:'この限定確認を破棄',click:discardCapture};if(result.classification==='full')render('完全データを保存しました','existing full validator・F3保存監査・read-back照合を通過しました。',[reviewAction,discardAction]);else if(result.classification==='partial')render('一部の材料を保存しました','計算できるかどうかは、この段階ではまだ判定していません。',[reviewAction,discardAction]);else render('このstageでは安全に保存できません','failure metadataだけを保持しました。',[reviewAction,discardAction]);}catch(error){busy=false;stopped(error);}}
async function openReview(){try{const batch=await createTypedInspectionBatch({session});window.location.href=`../phase11-typed-inspection/index.html#batch=${encodeURIComponent(JSON.stringify(batch))}`;}catch(error){stopped(error);}}
async function discardCapture(){if(!activeCapture)return;try{await discardF3Capture({retention,captureId:activeCapture.id,removeArtifacts:async()=>{const current=await session.load();for(const entry of Object.values(current?.drafts??{})){await draftStore.removeDraft(entry.draftDigest);await draftStore.removePayload(entry.contentDigest);}for(const entry of Object.values(current?.failures??{}))await draftStore.removeFailure(entry.failureDigest);await backend.clear();return true;}});activeCapture=null;render('限定確認を破棄しました','snapshotは保存されておらず、関連session/draft/material/failure indexを削除しました。',[{label:'fixtureを選び直す',click:choose}]);}catch(error){stopped(error);}}
function choose(){render('F3-prep fixtureを選択','すべて自作HTMLです。実サイト・通信・XPIには接続しません。',[{label:'FULL fixture',click:()=>select(fullFixture,'F3 完全fixture')},{label:'PARTIAL fixture',click:()=>select(partialFixture,'F3 部分fixture')},{label:'UNUSABLE fixture',click:()=>select(unusableFixture,'F3 停止fixture')}]);}
choose();
